-- Freelance CRM — Initial schema matching data.js
-- Run with: supabase db push (or apply via Supabase dashboard)

-- Clients (from CLIENTS)
create table if not exists public.clients (
  id bigint primary key generated by default as identity,
  name text not null,
  contact text,
  email text,
  phone text,
  stage text,
  type text,
  value numeric default 0,
  outstanding numeric default 0,
  started text,
  tags jsonb default '[]',
  avatar text,
  color text,
  last_activity text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

comment on table public.clients is 'CRM clients; maps to CLIENTS in data.js';

-- Projects (from PROJECTS) — references clients by name in data.js; we use client_id
create table if not exists public.projects (
  id bigint primary key generated by default as identity,
  client_id bigint not null references public.clients(id) on delete cascade,
  name text not null,
  status text,
  type text,
  budget numeric default 0,
  billed numeric default 0,
  deadline text,
  progress int default 0,
  hours numeric default 0,
  est_hours numeric default 0,
  tags jsonb default '[]',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_projects_client_id on public.projects(client_id);
comment on table public.projects is 'Projects per client; maps to PROJECTS in data.js';

-- Invoices (from INVOICES)
create table if not exists public.invoices (
  id text primary key,
  client_id bigint not null references public.clients(id) on delete restrict,
  amount numeric not null,
  status text,
  issued text,
  due text,
  paid text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_invoices_client_id on public.invoices(client_id);
create index if not exists idx_invoices_status on public.invoices(status);

-- Invoice line items (from INVOICES[].items)
create table if not exists public.invoice_items (
  id bigint primary key generated by default as identity,
  invoice_id text not null references public.invoices(id) on delete cascade,
  "desc" text,
  rate numeric default 0,
  sort_order int default 0
);

create index if not exists idx_invoice_items_invoice_id on public.invoice_items(invoice_id);
comment on table public.invoice_items is 'Line items for each invoice; maps to INVOICES[].items';

-- Proposals (from PROPOSALS)
create table if not exists public.proposals (
  id text primary key,
  client_id bigint not null references public.clients(id) on delete restrict,
  title text,
  value numeric default 0,
  status text,
  sent text,
  expires text,
  win int default 0,
  type text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_proposals_client_id on public.proposals(client_id);
create index if not exists idx_proposals_status on public.proposals(status);

-- Time logs (from TIME_LOGS) — client/project can be null for internal time
create table if not exists public.time_logs (
  id bigint primary key generated by default as identity,
  date text not null,
  client_id bigint references public.clients(id) on delete set null,
  project_id bigint references public.projects(id) on delete set null,
  "desc" text,
  hours numeric not null default 0,
  billable boolean default true,
  rate numeric default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_time_logs_client_id on public.time_logs(client_id);
create index if not exists idx_time_logs_project_id on public.time_logs(project_id);
create index if not exists idx_time_logs_date on public.time_logs(date);

-- Tasks (from TASKS_DATA)
create table if not exists public.tasks (
  id bigint primary key generated by default as identity,
  text text not null,
  due text,
  client_id bigint references public.clients(id) on delete set null,
  priority text default 'medium',
  done boolean default false,
  category text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_tasks_client_id on public.tasks(client_id);
create index if not exists idx_tasks_done on public.tasks(done);
create index if not exists idx_tasks_priority on public.tasks(priority);

-- Optional: updated_at trigger
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'clients_updated_at') then
    create trigger clients_updated_at before update on public.clients
      for each row execute function public.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'projects_updated_at') then
    create trigger projects_updated_at before update on public.projects
      for each row execute function public.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'invoices_updated_at') then
    create trigger invoices_updated_at before update on public.invoices
      for each row execute function public.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'proposals_updated_at') then
    create trigger proposals_updated_at before update on public.proposals
      for each row execute function public.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'time_logs_updated_at') then
    create trigger time_logs_updated_at before update on public.time_logs
      for each row execute function public.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'tasks_updated_at') then
    create trigger tasks_updated_at before update on public.tasks
      for each row execute function public.set_updated_at();
  end if;
end $$;

-- RLS: enable and allow read/write for authenticated users (adjust to your auth)
alter table public.clients enable row level security;
alter table public.projects enable row level security;
alter table public.invoices enable row level security;
alter table public.invoice_items enable row level security;
alter table public.proposals enable row level security;
alter table public.time_logs enable row level security;
alter table public.tasks enable row level security;

-- Policies: allow all for anon so app works before auth (tighten in production)
create policy "clients_select" on public.clients for select using (true);
create policy "clients_insert" on public.clients for insert with check (true);
create policy "clients_update" on public.clients for update using (true);
create policy "clients_delete" on public.clients for delete using (true);

create policy "projects_select" on public.projects for select using (true);
create policy "projects_insert" on public.projects for insert with check (true);
create policy "projects_update" on public.projects for update using (true);
create policy "projects_delete" on public.projects for delete using (true);

create policy "invoices_select" on public.invoices for select using (true);
create policy "invoices_insert" on public.invoices for insert with check (true);
create policy "invoices_update" on public.invoices for update using (true);
create policy "invoices_delete" on public.invoices for delete using (true);

create policy "invoice_items_select" on public.invoice_items for select using (true);
create policy "invoice_items_insert" on public.invoice_items for insert with check (true);
create policy "invoice_items_update" on public.invoice_items for update using (true);
create policy "invoice_items_delete" on public.invoice_items for delete using (true);

create policy "proposals_select" on public.proposals for select using (true);
create policy "proposals_insert" on public.proposals for insert with check (true);
create policy "proposals_update" on public.proposals for update using (true);
create policy "proposals_delete" on public.proposals for delete using (true);

create policy "time_logs_select" on public.time_logs for select using (true);
create policy "time_logs_insert" on public.time_logs for insert with check (true);
create policy "time_logs_update" on public.time_logs for update using (true);
create policy "time_logs_delete" on public.time_logs for delete using (true);

create policy "tasks_select" on public.tasks for select using (true);
create policy "tasks_insert" on public.tasks for insert with check (true);
create policy "tasks_update" on public.tasks for update using (true);
create policy "tasks_delete" on public.tasks for delete using (true);
