-- HopeCRM / Nonprofit CRM — Initial schema (mirrors data.js)
-- Apply: supabase db reset (local) or run in Dashboard SQL Editor (hosted)

-- Donors (from DONORS)
create table if not exists public.donors (
  id bigint primary key generated by default as identity,
  name text not null,
  type text,
  tier text,
  stage text,
  ltv numeric default 0,
  last_gift numeric default 0,
  last_date text,
  source text,
  staff text,
  email text,
  phone text,
  notes text,
  tags jsonb default '[]',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

comment on table public.donors is 'Donors and contacts; maps to DONORS in data.js';

-- Grants (from GRANTS)
create table if not exists public.grants (
  id bigint primary key generated by default as identity,
  funder text not null,
  amount numeric default 0,
  deadline text,
  stage text,
  program text,
  staff text,
  report_due text,
  submitted text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_grants_stage on public.grants(stage);
create index if not exists idx_grants_funder on public.grants(funder);

-- Campaigns (from CAMPAIGNS)
create table if not exists public.campaigns (
  id bigint primary key generated by default as identity,
  name text not null,
  type text,
  goal numeric default 0,
  raised numeric default 0,
  donors_count int default 0,
  start_date text,
  end_date text,
  status text,
  color text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_campaigns_status on public.campaigns(status);

-- Events (from EVENTS)
create table if not exists public.events (
  id bigint primary key generated by default as identity,
  name text not null,
  type text,
  date text,
  venue text,
  capacity int default 0,
  registered int default 0,
  revenue_goal numeric default 0,
  revenue numeric default 0,
  status text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_events_status on public.events(status);

-- Volunteers (from VOLUNTEERS)
create table if not exists public.volunteers (
  id bigint primary key generated by default as identity,
  name text not null,
  skills jsonb default '[]',
  hours numeric default 0,
  availability text,
  status text,
  last_active text,
  events_count int default 0,
  email text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_volunteers_status on public.volunteers(status);

-- Tasks (from TASKS_DATA)
create table if not exists public.tasks (
  id bigint primary key generated by default as identity,
  text text not null,
  due text,
  staff text,
  priority text default 'medium',
  done boolean default false,
  category text,
  linked text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_tasks_done on public.tasks(done);
create index if not exists idx_tasks_staff on public.tasks(staff);

-- Email templates (from EMAIL_TEMPLATES)
create table if not exists public.email_templates (
  id bigint primary key generated by default as identity,
  name text not null,
  category text,
  opens int default 0,
  sent int default 0,
  subject text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Sequences (from SEQUENCES)
create table if not exists public.sequences (
  id bigint primary key generated by default as identity,
  name text not null,
  status text,
  contacts int default 0,
  emails int default 0,
  open_rate numeric default 0,
  next_step text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- updated_at trigger
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger donors_updated_at
  before update on public.donors for each row execute function public.set_updated_at();
create trigger grants_updated_at
  before update on public.grants for each row execute function public.set_updated_at();
create trigger campaigns_updated_at
  before update on public.campaigns for each row execute function public.set_updated_at();
create trigger events_updated_at
  before update on public.events for each row execute function public.set_updated_at();
create trigger volunteers_updated_at
  before update on public.volunteers for each row execute function public.set_updated_at();
create trigger tasks_updated_at
  before update on public.tasks for each row execute function public.set_updated_at();
create trigger email_templates_updated_at
  before update on public.email_templates for each row execute function public.set_updated_at();
create trigger sequences_updated_at
  before update on public.sequences for each row execute function public.set_updated_at();

-- RLS: enable (policies can be added per your auth)
alter table public.donors enable row level security;
alter table public.grants enable row level security;
alter table public.campaigns enable row level security;
alter table public.events enable row level security;
alter table public.volunteers enable row level security;
alter table public.tasks enable row level security;
alter table public.email_templates enable row level security;
alter table public.sequences enable row level security;

-- Allow read/write for anon and authenticated until you add proper policies
create policy "donors_select" on public.donors for select using (true);
create policy "donors_insert" on public.donors for insert with check (true);
create policy "donors_update" on public.donors for update using (true);
create policy "donors_delete" on public.donors for delete using (true);

create policy "grants_select" on public.grants for select using (true);
create policy "grants_insert" on public.grants for insert with check (true);
create policy "grants_update" on public.grants for update using (true);
create policy "grants_delete" on public.grants for delete using (true);

create policy "campaigns_select" on public.campaigns for select using (true);
create policy "campaigns_insert" on public.campaigns for insert with check (true);
create policy "campaigns_update" on public.campaigns for update using (true);
create policy "campaigns_delete" on public.campaigns for delete using (true);

create policy "events_select" on public.events for select using (true);
create policy "events_insert" on public.events for insert with check (true);
create policy "events_update" on public.events for update using (true);
create policy "events_delete" on public.events for delete using (true);

create policy "volunteers_select" on public.volunteers for select using (true);
create policy "volunteers_insert" on public.volunteers for insert with check (true);
create policy "volunteers_update" on public.volunteers for update using (true);
create policy "volunteers_delete" on public.volunteers for delete using (true);

create policy "tasks_select" on public.tasks for select using (true);
create policy "tasks_insert" on public.tasks for insert with check (true);
create policy "tasks_update" on public.tasks for update using (true);
create policy "tasks_delete" on public.tasks for delete using (true);

create policy "email_templates_select" on public.email_templates for select using (true);
create policy "email_templates_insert" on public.email_templates for insert with check (true);
create policy "email_templates_update" on public.email_templates for update using (true);
create policy "email_templates_delete" on public.email_templates for delete using (true);

create policy "sequences_select" on public.sequences for select using (true);
create policy "sequences_insert" on public.sequences for insert with check (true);
create policy "sequences_update" on public.sequences for update using (true);
create policy "sequences_delete" on public.sequences for delete using (true);
