export { default as DashboardPage } from "./DashboardPage";
export { default as ClientsPage } from "./ClientsPage";
export { default as ProjectsPage } from "./ProjectsPage";
export { default as InvoicesPage } from "./InvoicesPage";
export { default as ProposalsPage } from "./components/ProposalsPage";
export { default as TimeLogPage } from "./TimeLogPage";
export { default as TasksPage } from "./TasksPage";
export { default as ReportsPage } from "./ReportsPage";
export { default as SettingsPage } from "./SettingsPage";
